#!/usr/bin/env bash

# Set up vim with my personal vim-plugins
# Author: Christopher Markieta

MY_DIR=$(dirname $0)
os=$(gawk -F= '/^NAME/{print $2}' /etc/os-release | tr -d '"')

if [ "$os" == "Ubuntu" ]; then
    sudo apt-get install -y vim-gnome cmake python2.7-dev
else
       # yum install for older systems
    sudo yum install -y vim-X11 cmake python-devel gcc-c++
fi

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

cp "$MY_DIR"/.vimrc ~/
