#!/usr/bin/env bash

# Set up vim with my personal vim-plugins
# Author: Christopher Markieta

MY_DIR=$(dirname $0)

#    yum install for older systems
sudo dnf install -y vim cmake

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

cp "$MY_DIR"/.vimrc ~/

vi -c 'PlugInstall|q|q'
